# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
builds:
  - goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    id: server
    main: ./server
    binary: cfsecurity-server
  - goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    id: plugin
    main: ./plugin
    binary: cfsecurity-plugin
  - goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    id: provider
    main: ./terraform-provider-cfsecurity
    binary: terraform-provider-cfsecurity
archives:
  - id: zip-archive-server
    builds: [server]
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    format: zip
  - id: binary-archive-server
    builds: [server]
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    format: binary
  - id: zip-archive-plugin
    builds: [plugin]
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    format: zip
  - id: binary-archive-plugin
    builds: [plugin]
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    format: binary
  - id: zip-archive-provider
    builds: [provider]
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    format: zip
  - id: binary-archive-provider
    builds: [provider]
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    format: binary
checksum:
  name_template: 'checksums.txt'
  algorithm: sha1
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
